#!/bin/perl

print "createspf1 - create SPF1 records for the given domain\n";
print "=====================================================\n";

use strict;
use warnings;

my ($inputfile) = @ARGV;
my $curhost = "";
my $CredFile = "creds.txt";
my $DomainAdmin = "";
my $DomainPassword = "";

if (not defined $inputfile) {
	die "Need to specify input file\n";
}

open my $fh, '<', "$CredFile" or die $!;
while (<$fh>)
{
	# Read In the credentials
	chop();
	($DomainAdmin, $DomainPassword) = split('	', $_);
	print "Admin = $DomainAdmin, Password=$DomainPassword\n";
}
close $fh or die $!;


sub OutputLine
{
	print "v=spf1 a:$curhost.$inputfile mx:$curhost.$inputfile -all\n";
}
open $fh, '<', "$inputfile" or die $!;
while (<$fh>)
{
	# line contents's automatically stored in the $_ variable
	chop();
	$curhost = $_;
	OutputLine();
}
close $fh or die $!;

exit 0;
